CREATE USER prueba IDENTIFIED BY "CittTrackOpen202311!"
DEFAULT TABLESPACE "DATA"
TEMPORARY TABLESPACE "TEMP";
ALTER USER prueba QUOTA UNLIMITED ON DATA;
GRANT "RESOURCE" TO prueba;
ALTER USER prueba DEFAULT ROLE "RESOURCE";