
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.DaoTipoMovimiento;
import Modelo.TipoMovimiento;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class JfrmAgregarTipoMovimiento extends javax.swing.JFrame {

    /**
     */
    public JfrmAgregarTipoMovimiento() {
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JfrmAgregarTipoMovimiento.DO_NOTHING_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNombreTipoMovimiento = new javax.swing.JTextField();
        btnGrabarTipoMovimiento = new javax.swing.JButton();
        btnSalirTipoMovimiento = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("VALORANT", 0, 18)); // NOI18N
        jLabel1.setText("INGRESO DE Tipo Movimiento");

        txtNombreTipoMovimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreTipoMovimientoActionPerformed(evt);
            }
        });

        btnGrabarTipoMovimiento.setText("GRABAR");
        btnGrabarTipoMovimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrabarTipoMovimientoActionPerformed(evt);
            }
        });

        btnSalirTipoMovimiento.setText("Cerrar");
        btnSalirTipoMovimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirTipoMovimientoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(txtNombreTipoMovimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnGrabarTipoMovimiento))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(229, 229, 229)
                        .addComponent(btnSalirTipoMovimiento))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreTipoMovimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGrabarTipoMovimiento))
                .addGap(18, 18, 18)
                .addComponent(btnSalirTipoMovimiento)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGrabarTipoMovimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrabarTipoMovimientoActionPerformed
        try {
            int idTipoMovimiento = 0;
            String nombreTipoMovimiento = txtNombreTipoMovimiento.getText();
            TipoMovimiento tpMov = new TipoMovimiento(idTipoMovimiento, nombreTipoMovimiento);
            boolean resp = new DaoTipoMovimiento().Grabar(tpMov);
            if (resp) {
                JOptionPane.showMessageDialog(null, "Grabo");
            } else {
                JOptionPane.showMessageDialog(null, "No Grabo");
            }
        } catch (Exception e) {
            System.out.println("error grabar: "+e.getMessage());
            JOptionPane.showMessageDialog(null, "No se pudo grabar");
        }
    }//GEN-LAST:event_btnGrabarTipoMovimientoActionPerformed

    private void txtNombreTipoMovimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreTipoMovimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreTipoMovimientoActionPerformed

    private void btnSalirTipoMovimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirTipoMovimientoActionPerformed
        // TODO add your handling code here:
        mostrarMain();
    }//GEN-LAST:event_btnSalirTipoMovimientoActionPerformed

    private void mostrarMain(){
        this.dispose();
    
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JfrmAgregarTipoMovimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JfrmAgregarTipoMovimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JfrmAgregarTipoMovimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JfrmAgregarTipoMovimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JfrmAgregarTipoMovimiento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGrabarTipoMovimiento;
    private javax.swing.JButton btnSalirTipoMovimiento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtNombreTipoMovimiento;
    // End of variables declaration//GEN-END:variables
}
